version: "3"
services:

  Server:
    image: nikolaykostandiev/crypto_server:${IMAGE_TAG}
    ports: 
      - 7777:7777
    environment:
      - API_KEY: "${{secrets.API_KEY}}"

  Client:
    image: nikolaykostandiev/crypto_client:${IMAGE_TAG}
    network_host: host
    depends_on:
      - Server
