version: "3"
services:

  Server:
    image: nikolaykostandiev/crypto_server:6ae47db4486e24d60df158796213ae5dc547b4da
    ports: 
      - 7777:7777
    environment:
      - API_KEY: "${{secrets.API_KEY}}"

  Client:
    image: nikolaykostandiev/crypto_client:6ae47db4486e24d60df158796213ae5dc547b4da
    network_host: host
    depends_on:
      - Server
