version: "3"
services:

  Server:
    image: nikolaykostandiev/crypto_server:${IMAGE_TAG}
    container_name: Server
    environment:
      - API_KEY=${{secrets.API_KEY}}
      - LISTEN_PORT=${PORT}

  Client:
    image: nikolaykostandiev/crypto_client:${IMAGE_TAG}
    container_name: Client
    restart: on-failure
    environment:
      - SERVER_PORT=${PORT}
      - HOST_NAME=Server
    depends_on:
      - Server
